Server:
    port: 8081
spring:
    mail:
        host: smtp.gmail.com
        username: carbonohelp@gmail.com
        password: pddwnpzrdirnhfph
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
    application:
            name: user
    datasource:
        password: zhaoxing
        url: jdbc:postgresql://3.0.239.64:5432/user
#        url: jdbc:postgresql://localhost:5432/user
        username: postgres
        #username need to change to postgres when deploying (ec2 is postgres)
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
        show-sql: true
eureka:
    client:
        service-url:
            defaultZone: http://3.0.239.64:8761/eureka/
#            defaultZone: http://localhost:8761/eureka/
        fetch-registry: true
        register-with-eureka: true
    instance:
        prefer-ip-address: true

