spring:
  application:
    name: eureka-server

server:
  port: 8761
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: password
#    key-store-type: PKCS12
#    key-alias: tomcat
#    enabled: true

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
