Server:
    port: 8082
spring:
    application:
            name: carbonTracker
    datasource:
        password: zhaoxing
        url: jdbc:postgresql://3.0.21.36:5432/carbontracker
#        url: jdbc:postgresql://localhost:5432/carbontracker
        username: postgres
    jpa:
        hibernate:
            ddl-auto: create-drop

        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
                globally_quoted_identifiers: true
        show-sql: true

eureka:
    client:
        service-url:
            defaultZone: http://18.136.163.9:8761/eureka/
#            defaultZone: http://localhost:8761/eureka/
        fetch-registry: true
        register-with-eureka: true
    instance:
        prefer-ip-address: true
        ip-address: 3.0.21.36

