Server:
    port: 8082
spring:
    application:
            name: carbonTracker
    datasource:
        password: zhaoxing
        url: jdbc:postgresql://localhost:5434/carbonTracker
        username: xxhea
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
        show-sql: true


