Server:
    port: 8082
spring:
    application:
            name: carbonTracker
    datasource:
        password: 123
        url: jdbc:postgresql://localhost:5432/carbonTracker
        username: chong
    jpa:
        hibernate:
            ddl-auto: create-drop

        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
                globally_quoted_identifiers: true
        show-sql: true

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
        fetch-registry: true
        register-with-eureka: true

