# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CarbonO CI/CD 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: 
      name: Production
      url: https://github.com
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
        cache: maven
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build user with Maven and push image
      env:
          CARBONO_USERNAME: ${{ secrets.CARBONO_USERNAME  }}
          CARBONO_PASSWORD: ${{ secrets.CARBONO_PASSWORD  }}
      working-directory: ./carbonO/user
      run: |
        mvn clean package dockerfile:push
      
    - name: Build carbonTracker with Maven and push image
      working-directory: ./carbonO/carbonTracker
      run: |
        mvn clean install
        mvn clean package dockerfile:push
        
    - name: Build userReward with Maven and push image
      working-directory: ./carbonO/userReward
      run: |
        mvn clean package dockerfile:push 
